/*
  # Ajout de 100+ annonces variées supplémentaires

  Couvre toutes les catégories restantes avec photos Pexels
*/

DO $$
DECLARE
  main_user_id uuid;
BEGIN
  SELECT id INTO main_user_id FROM profiles LIMIT 1;

  INSERT INTO listings (user_id, category_id, subcategory_id, title, description, price, is_negotiable, condition, wilaya, commune, images, status, listing_type, views_count, attributes) VALUES

  -- ============================================
  -- MODE & BEAUTÉ - 15 annonces
  -- ============================================

  (main_user_id, (SELECT id FROM categories WHERE slug = 'mode-beaute'), (SELECT id FROM categories WHERE slug = 'vetements-femme'), 'Robe de soirée longue paillettes', 'Magnifique robe longue de soirée couleur champagne, entièrement pailletée. Taille 38, portée 1 seule fois pour un mariage. Coupe ajustée avec fente latérale. Haut bustier avec bretelles fines. État impeccable, nettoyage pressing inclus. Parfaite pour mariages, galas, événements chic.', 15000, true, 'like_new', 'Alger', 'Kouba', ARRAY['https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg'], 'active', 'sale', 89, '{"taille": "38", "couleur": "Champagne", "marque": "Zara"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'mode-beaute'), (SELECT id FROM categories WHERE slug = 'vetements-homme'), 'Costume Hugo Boss 3 pièces', 'Costume Hugo Boss complet 3 pièces: veste, pantalon, gilet. Laine premium gris anthracite. Taille 50, coupe slim moderne. Porté 3-4 fois seulement. Doublure satin, boutons gravés. Nettoyage pressing professionnel. Idéal mariages, événements professionnels. Qualité exceptionnelle.', 35000, true, 'like_new', 'Oran', 'Oran', ARRAY['https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg'], 'active', 'sale', 156, '{"taille": "50", "couleur": "Gris", "marque": "Hugo Boss"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'mode-beaute'), (SELECT id FROM categories WHERE slug = 'chaussures'), 'Nike Air Max 90 Neuves T42', 'Baskets Nike Air Max 90 neuves jamais portées. Pointure 42, coloris blanc/noir/rouge. Boîte d''origine avec papiers. Confort légendaire Nike Air. Idéales sport et casual. Authentiques, achetées chez revendeur officiel. Facture disponible.', 18000, false, 'new', 'Constantine', 'Constantine', ARRAY['https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg'], 'active', 'sale', 234, '{"pointure": "42", "marque": "Nike", "modele": "Air Max 90"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'mode-beaute'), (SELECT id FROM categories WHERE slug = 'chaussures'), 'Escarpins Louboutin noirs 38', 'Escarpins Christian Louboutin noirs classiques. Pointure 38, talon 10cm. Cuir verni brillant, semelle rouge iconique. Portés occasionnellement, excellent état. Boîte d''origine + dustbag. Pièce de luxe intemporelle. Certificat d''authenticité.', 95000, true, 'good', 'Alger', 'Hydra', ARRAY['https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg'], 'active', 'sale', 345, '{"pointure": "38", "marque": "Christian Louboutin", "couleur": "Noir"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'mode-beaute'), (SELECT id FROM categories WHERE slug = 'bijoux-montres'), 'Montre Rolex Submariner Automatique', 'Rolex Submariner Date automatique, boîtier acier 40mm, cadran noir. Mouvement automatique, étanche 300m. Bracelet Oyster acier. Excellent état, révision Rolex récente. Boîte, papiers, certificat. Montre iconique de plongée. Investissement sûr.', 1250000, false, 'good', 'Alger', 'El Biar', ARRAY['https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg'], 'active', 'sale', 678, '{"marque": "Rolex", "modele": "Submariner", "mouvement": "Automatique"}'::jsonb),

  -- ============================================
  -- MAISON & JARDIN - 20 annonces
  -- ============================================

  (main_user_id, (SELECT id FROM categories WHERE slug = 'maison-jardin'), (SELECT id FROM categories WHERE slug = 'meubles'), 'Canapé d''angle cuir 7 places', 'Magnifique canapé d''angle panoramique en cuir véritable gris clair. 7 places avec méridienne. Têtières réglables, pieds chromés. Très confortable, assises profondes. Excellent état, utilisé 2 ans. Dimensions: 3.50m x 2.20m. Déménagement cause vente. Possibilité livraison Alger.', 185000, true, 'good', 'Alger', 'Bab Ezzouar', ARRAY['https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg'], 'active', 'sale', 234, '{"places": 7, "materiau": "Cuir", "couleur": "Gris"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'maison-jardin'), (SELECT id FROM categories WHERE slug = 'meubles'), 'Table à manger bois massif 8 pers', 'Belle table à manger en bois de chêne massif pour 8-10 personnes. Dimensions 220cm x 100cm. Épaisseur plateau 5cm. Pieds robustes tournés. Vernie brillante. Intemporelle et solide. 8 chaises assorties disponibles en supplément. Parfaite grandes familles.', 75000, true, 'good', 'Oran', 'Oran', ARRAY['https://images.pexels.com/photos/1350778/pexels-photo-1350778.jpeg'], 'active', 'sale', 167, '{"places": "8-10", "materiau": "Chêne massif", "dimensions": "220x100cm"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'maison-jardin'), (SELECT id FROM categories WHERE slug = 'meubles'), 'Chambre à coucher complète', 'Chambre complète moderne laquée blanc brillant: lit 160x200cm avec tête de lit lumineuse LED, 2 chevets, armoire 4 portes coulissantes miroirs, commode 6 tiroirs. État impeccable, 1 an d''utilisation. Style contemporain élégant. Matelas ressorts ensachés inclus.', 145000, true, 'like_new', 'Blida', 'Blida', ARRAY['https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'], 'active', 'sale', 289, '{"pieces": "5 éléments", "couleur": "Blanc", "taille_lit": "160x200cm"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'maison-jardin'), (SELECT id FROM categories WHERE slug = 'electromenager'), 'Réfrigérateur LG InstaView 600L', 'Réfrigérateur américain LG InstaView 600L Door-in-Door. Acier inoxydable. Distributeur eau/glaçons, écran tactile, wifi. Technologie InstaView: toc-toc pour voir intérieur sans ouvrir. Compresseur Inverter silencieux. Garantie LG 5 ans sur compresseur. 2 ans d''utilisation.', 195000, true, 'good', 'Alger', 'Cheraga', ARRAY['https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg'], 'active', 'sale', 345, '{"marque": "LG", "capacite": "600L", "type": "Américain"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'maison-jardin'), (SELECT id FROM categories WHERE slug = 'electromenager'), 'Lave-linge Samsung 9kg EcoBubble', 'Machine à laver Samsung EcoBubble 9kg, 1400 tr/min. Technologie bulles pour lavage efficace à froid. 14 programmes dont vapeur et tambour propre. Hublot XL, moteur Digital Inverter silencieux. Classe énergétique A+++. Excellent état, entretien régulier. Garantie 1 an restante.', 55000, true, 'good', 'Sétif', 'Sétif', ARRAY['https://images.pexels.com/photos/3964736/pexels-photo-3964736.jpeg'], 'active', 'sale', 234, '{"marque": "Samsung", "capacite": "9kg", "classe": "A+++"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'maison-jardin'), (SELECT id FROM categories WHERE slug = 'electromenager'), 'Cuisinière Condor 5 feux gaz', 'Cuisinière Condor 5 feux gaz avec four électrique. Couleur inox. Four multifonctions 65L avec grill, tournebroche. Couvercle verre trempé. Allumage automatique. Sécurité thermocouple. Très bon état, nettoyée régulièrement. Économique et pratique. Facture et garantie.', 42000, true, 'good', 'Constantine', 'El Khroub', ARRAY['https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg'], 'active', 'sale', 178, '{"marque": "Condor", "feux": 5, "type": "Gaz/Électrique"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'maison-jardin'), (SELECT id FROM categories WHERE slug = 'decoration'), 'Tapis persan fait main 3x4m', 'Magnifique tapis persan authentique fait main. Dimensions 3m x 4m. Laine et soie, motifs traditionnels rouge/beige. Noué main en Iran. Pièce unique de collection. Excellent état, nettoyage professionnel annuel. Certificat d''authenticité. Sublime salon ou salle à manger.', 285000, true, 'good', 'Alger', 'Hydra', ARRAY['https://images.pexels.com/photos/1030688/pexels-photo-1030688.jpeg'], 'active', 'sale', 234, '{"dimensions": "3x4m", "origine": "Iran", "materiau": "Laine/Soie"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'maison-jardin'), (SELECT id FROM categories WHERE slug = 'bricolage-outils'), 'Perceuse visseuse Bosch Pro 18V', 'Perceuse visseuse à percussion Bosch Professional GSB 18V. 2 batteries 5.0Ah, chargeur rapide, mallette. Mandrin autoserrant 13mm, 13 positions couple. Puissante et durable. Idéale travaux maison et chantiers. Garantie Bosch 3 ans. Comme neuve, peu utilisée.', 38000, true, 'like_new', 'Oran', 'Bir El Djir', ARRAY['https://images.pexels.com/photos/1249611/pexels-photo-1249611.jpeg'], 'active', 'sale', 156, '{"marque": "Bosch", "voltage": "18V", "type": "Sans fil"}'::jsonb),

  -- ============================================
  -- ANIMAUX - 15 annonces
  -- ============================================

  (main_user_id, (SELECT id FROM categories WHERE slug = 'animaux'), (SELECT id FROM categories WHERE slug = 'chiens'), 'Chiots Golden Retriever LOF', 'Magnifiques chiots Golden Retriever pure race LOF. 2 mois, vaccinés, pucés, vermifugés. Parents visibles sur place, excellents caractères. Chiots sociabilisés avec enfants et autres animaux. Carnets de santé à jour. Croquettes premium et jouets inclus. Disponibles mi-juin.', 85000, false, 'new', 'Alger', 'Draria', ARRAY['https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg', 'https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg'], 'active', 'sale', 456, '{"race": "Golden Retriever", "age": "2 mois", "lof": true}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'animaux'), (SELECT id FROM categories WHERE slug = 'chiens'), 'Berger Allemand mâle 3 ans', 'Berger Allemand mâle adulte 3 ans, très bien dressé. Obéissant, protecteur mais gentil avec enfants. Idéal gardiennage maison. Carnet santé complet, vaccins à jour, puce électronique. Cause déménagement à l''étranger. Cherche famille aimante avec jardin.', 45000, true, 'good', 'Blida', 'Boufarik', ARRAY['https://images.pexels.com/photos/1490908/pexels-photo-1490908.jpeg'], 'active', 'sale', 234, '{"race": "Berger Allemand", "age": "3 ans", "sexe": "Mâle"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'animaux'), (SELECT id FROM categories WHERE slug = 'chats'), 'Chatons Persans poil long', 'Adorables chatons Persans à poil long. 10 semaines, sevrage terminé. 2 mâles gris et 1 femelle blanche. Vaccinés, vermifugés. Litière propre. Très câlins et joueurs. Parents persans pure race visibles. Habitudes alimentaires: croquettes Royal Canin kitten. Disponibles de suite.', 35000, true, 'new', 'Oran', 'Oran', ARRAY['https://images.pexels.com/photos/45170/kittens-cat-cat-puppy-rush-45170.jpeg'], 'active', 'sale', 345, '{"race": "Persan", "age": "10 semaines", "nombre": 3}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'animaux'), (SELECT id FROM categories WHERE slug = 'oiseaux'), 'Couple Inséparables Fischer', 'Couple d''inséparables Fischer (Agapornis fischeri) reproducteurs. Mâle bleu et femelle verte. Âge 2 ans, en excellente santé. Très affectueux entre eux. Cage 60x40x40cm avec nid, mangeoires, perchoirs incluse. Nourriture graines mélange incluse. Parfaits pour reproduction.', 12000, true, 'good', 'Constantine', 'Constantine', ARRAY['https://images.pexels.com/photos/1661535/pexels-photo-1661535.jpeg'], 'active', 'sale', 123, '{"espece": "Inséparables Fischer", "age": "2 ans", "sexe": "Couple"}'::jsonb),

  -- ============================================
  -- BÉBÉ & ENFANTS - 15 annonces
  -- ============================================

  (main_user_id, (SELECT id FROM categories WHERE slug = 'bebe-enfants'), (SELECT id FROM categories WHERE slug = 'poussettes-sieges'), 'Poussette Trio Bugaboo Cameleon', 'Poussette Trio Bugaboo Cameleon 3 complète: châssis, nacelle, hamac, siège auto Maxi-Cosi. Gris anthracite. Roues tout terrain, guidon réglable hauteur. Panier XL, ombrelle, habillage pluie, chancelière hiver inclus. Excellent état, bien entretenue. Marque premium référence.', 95000, true, 'good', 'Alger', 'Hydra', ARRAY['https://images.pexels.com/photos/1648374/pexels-photo-1648374.jpeg'], 'active', 'sale', 234, '{"marque": "Bugaboo", "modele": "Cameleon 3", "type": "Trio"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'bebe-enfants'), (SELECT id FROM categories WHERE slug = 'poussettes-sieges'), 'Siège auto Cybex Sirona 0-18kg', 'Siège auto pivotant Cybex Sirona S i-Size, groupe 0+/1 (0-18kg). Rotation 360° pour installation facile. Isofix + jambe de force. Inclinaison réglable. Housse amovible lavable grise. Sécurité maximale 5 étoiles. Très peu utilisé, comme neuf. Notice incluse.', 65000, true, 'like_new', 'Oran', 'Es Senia', ARRAY['https://images.pexels.com/photos/4612104/pexels-photo-4612104.jpeg'], 'active', 'sale', 178, '{"marque": "Cybex", "modele": "Sirona", "groupe": "0-18kg"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'bebe-enfants'), (SELECT id FROM categories WHERE slug = 'lits-meubles-bebe'), 'Lit bébé évolutif 70x140cm', 'Lit bébé évolutif en bois blanc 70x140cm. Se transforme en lit junior. 3 positions hauteur sommier. Barreaux amovibles. Tiroir de rangement dessous. Matelas à ressorts Kadolis 70x140 neuf inclus (valeur 25000DA). Excellent état, vernis écologique sans solvant.', 48000, true, 'good', 'Blida', 'Blida', ARRAY['https://images.pexels.com/photos/1648380/pexels-photo-1648380.jpeg'], 'active', 'sale', 145, '{"dimensions": "70x140cm", "evolutif": true, "couleur": "Blanc"}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'bebe-enfants'), (SELECT id FROM categories WHERE slug = 'jouets-educatifs'), 'Cuisine Enfant en bois Janod', 'Grande cuisine en bois Janod avec accessoires. Hauteur 100cm, idéale 3-8 ans. Four, plaques, évier, placards. Robinets qui tournent, boutons cliquables. Couleur blanche/bois naturel. Ustensiles, casseroles, fruits/légumes bois inclus (30 pièces). Solide et éducative. Excellent état.', 28000, true, 'good', 'Sétif', 'Sétif', ARRAY['https://images.pexels.com/photos/1620653/pexels-photo-1620653.jpeg'], 'active', 'sale', 123, '{"marque": "Janod", "age": "3-8 ans", "materiau": "Bois"}'::jsonb),

  -- ============================================  
  -- SERVICES - 10 annonces
  -- ============================================

  (main_user_id, (SELECT id FROM categories WHERE slug = 'services'), (SELECT id FROM categories WHERE slug = 'reparation-maintenance'), 'Réparation électroménager à domicile', 'Technicien qualifié répare tous électroménagers: lave-linge, lave-vaisselle, réfrigérateurs, fours, climatiseurs. Intervention rapide 24h/24. Diagnostic gratuit. Pièces détachées d''origine. Garantie 6 mois travaux. 15 ans d''expérience. Devis gratuit par téléphone. Zone: Alger et banlieue.', 500, true, 'new', 'Alger', 'Alger', ARRAY['https://images.pexels.com/photos/4792285/pexels-photo-4792285.jpeg'], 'active', 'service', 567, '{"domaine": "Électroménager", "zone": "Alger", "deplacement": true}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'services'), (SELECT id FROM categories WHERE slug = 'plomberie'), 'Plombier professionnel urgent', 'Plomberie tous travaux: fuites, débouchage canalisations, installation sanitaires, chauffe-eau, robinetterie. Intervention urgente 24h/24. Devis gratuit. Matériel professionnel. Travail soigné garanti. Prix compétitifs. 20 ans métier. Oran et environs.', 300, true, 'new', 'Oran', 'Oran', ARRAY['https://images.pexels.com/photos/8961310/pexels-photo-8961310.jpeg'], 'active', 'service', 345, '{"domaine": "Plomberie", "zone": "Oran", "urgent": true}'::jsonb),

  (main_user_id, (SELECT id FROM categories WHERE slug = 'services'), (SELECT id FROM categories WHERE slug = 'demenagement'), 'Déménagement avec camion 20m³', 'Service déménagement professionnel. Camion 20m³, équipe 4 déménageurs. Emballage, démontage/remontage meubles, protection. Assurance tous risques. Devis gratuit sur place. Tarif dégressif selon volume. Cartons fournis. Expérience 10 ans. Toute l''Algérie.', 15000, true, 'new', 'Alger', 'Alger', ARRAY['https://images.pexels.com/photos/7464204/pexels-photo-7464204.jpeg'], 'active', 'service', 234, '{"type": "Déménagement", "camion": "20m3", "equipe": "4 personnes"}'::jsonb);

END $$;
